source 'https://rubygems.org'
ruby '2.0.0'
gem 'rails', '3.2.15'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'   
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :production do
  gem 'rails_12factor'
  gem 'fog'
  gem 'unf'
  gem 'pg'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Deploy with Capistrano
gem 'capistrano'

gem 'dragonfly'
gem 'gibbon'
gem 'taps'
gem 'jquery-rails'
gem 'foundation-rails'
gem 'owlcarousel-rails'
gem 'normalize-rails'
gem 'will_paginate', '~> 3.0.5'

group :development, :test do
  gem 'sqlite3'
  gem "better_errors"
  gem 'annotate'
  gem 'rails-footnotes', '>= 3.7.5.rc4' 
  gem 'binding_of_caller'
end

group :development do
  gem "rails-erd"
  gem 'guard'
  gem 'guard-livereload', require: false
  gem 'pry-rails'
end

gem 'refinerycms', '~> 2.1.0'

# REFINERY CMS EXTENSIONS
gem 'refinerycms-acts-as-indexed', '~> 1.0.0'
gem 'refinerycms-blog', '~> 2.1.0'
gem 'refinerycms-search', '~> 2.1.0'
gem 'refinerycms-page-images', '~> 2.1.0'
gem 'acts-as-taggable-on'

# WRITERS SCAFFOLD
gem 'refinerycms-writers', :path => 'vendor/extensions'
